version: "1.0"
default-project: cli
projects:
  cli:
    default-environment: production
    environments:
      production:
        region: yul
        compose-files:
        - file:compose.mealie.yaml
