services:
  n8n:
    image: n8nio/n8n:1.105.3
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=UTC
      - TZ=UTC
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data:
