version: "1.0"
default-project: audiobookshelf
projects:
  audiobookshelf:
    default-environment: production
    environments:
      production:
        region: yul
        compose-files:
        - file:compose.yaml
