services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - audiobooks:/audiobooks
      - podcasts:/podcasts
      - metadata:/metadata
      - config:/config
    restart: unless-stopped

volumes:
  audiobooks:
  config:
  metadata:
  podcasts:
